"use client";

import { History } from "lucide-react";

export default function HistoryHeader() {
  return (
    <div className="mb-8 flex items-center justify-between">

      <div className="flex items-center gap-4">

        <div
          className="
            flex
            h-14
            w-14
            items-center
            justify-center
            rounded-2xl
            border
            border-cyan-500/20
            bg-cyan-500/10
          "
        >
          <History
            size={26}
            className="text-cyan-400"
          />
        </div>

        <div>

          <h1 className="text-3xl font-bold text-white">
            Analysis History
          </h1>

          <p className="mt-1 text-sm text-zinc-500">
            Every research generated by X6 Forge.
          </p>

        </div>

      </div>

    </div>
  );
}